# Generated by Django 5.2.7 on 2025-10-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GallinaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lote', models.CharField(max_length=100)),
                ('cantidad_gallinas', models.IntegerField(default=50)),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('huevos_buenos', models.IntegerField(default=0)),
                ('huevos_rotos', models.IntegerField(default=0)),
                ('huevos_defectuosos', models.IntegerField(default=0)),
                ('celdas_vendidas', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.gallinalote')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('lote', 'fecha')},
            },
        ),
    ]
